// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using AlgoJudge.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlgoJudge.Server.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260905233444_InstanceSignInRedirects")]
    partial class InstanceSignInRedirects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.AccessKey", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("AccessKeys", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.AccountDeletionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<string>("Detail")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("ExecuteAfter")
                        .HasColumnType("timestamptz");

                    b.Property<string>("HaltedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamptz");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProviderId", "RequestId")
                        .IsUnique()
                        .HasFilter("\"RequestId\" IS NOT NULL");

                    b.HasIndex("State", "ExecuteAfter");

                    b.ToTable("AccountDeletionRequests", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.AccountMerge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnonymiseAfter")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("MergedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("MergedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Moved")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("SourceAnonymisedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("SourceUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("UndoneAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UndoneByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("SourceUserId");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("SourceAnonymisedAt", "AnonymiseAfter");

                    b.ToTable("AccountMerges", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("HasQuestions")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideEndedSeriesProblems")
                        .HasColumnType("boolean");

                    b.Property<string>("JoinPassword")
                        .HasColumnType("text");

                    b.Property<int>("JoinPolicy")
                        .HasColumnType("integer");

                    b.Property<int>("MaxAttachments")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxSubmissionsPerProblem")
                        .HasColumnType("integer");

                    b.Property<long>("MaxUploadBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Props")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("RankingType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.PrimitiveCollection<List<string>>("RunnerTags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<int>("ScoreVisibility")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowGroupMembers")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Unlisted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Unlisted", "ArchivedAt");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.ActivityGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "Name")
                        .IsUnique();

                    b.ToTable("ActivityGroups", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.AttachmentRule", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("ActivityId", "Name");

                    b.ToTable("AttachmentRules", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.EvaluationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Deliveries")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("LeaseSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProblemVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Refunds")
                        .HasColumnType("integer");

                    b.Property<int>("Releases")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("RunnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LeaseExpiresAt");

                    b.HasIndex("LeaseToken")
                        .IsUnique()
                        .HasFilter("\"LeaseToken\" IS NOT NULL");

                    b.HasIndex("ProblemVersionId");

                    b.HasIndex("RunnerId");

                    b.HasIndex("SubmissionId")
                        .HasFilter("\"State\" = 1");

                    b.HasIndex("State", "CreatedAt")
                        .HasFilter("\"State\" < 2");

                    b.HasIndex("SubmissionId", "Attempt")
                        .IsUnique();

                    b.ToTable("EvaluationJobs", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.FederatedSignInAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("ChangedPermissions")
                        .HasColumnType("boolean");

                    b.Property<string>("Detail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Matched")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "At");

                    b.HasIndex("UserId", "At");

                    b.ToTable("FederatedSignInAttempts", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("PreviousCopyDeleteAfter")
                        .HasColumnType("timestamptz");

                    b.Property<string>("PreviousStorageId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("UploadedByRunnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("UploadedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PreviousCopyDeleteAfter")
                        .HasDatabaseName("IX_Files_PendingCopySweep")
                        .HasFilter("\"PreviousCopyDeleteAfter\" IS NOT NULL");

                    b.HasIndex("Sha256");

                    b.HasIndex("StorageId");

                    b.HasIndex("UploadedByRunnerId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.FileReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("EvaluationJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("OwnerKind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProblemVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RunnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SupersededAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("EvaluationJobId");

                    b.HasIndex("FileId");

                    b.HasIndex("InstanceId");

                    b.HasIndex("ProblemVersionId");

                    b.HasIndex("RunnerId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("OwnerKind", "SupersededAt");

                    b.ToTable("FileReferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_FileReferences_OwnerKindMatches", "(\"OwnerKind\" = 0 AND \"ProblemVersionId\" IS NOT NULL) OR (\"OwnerKind\" = 1 AND \"ActivityId\" IS NOT NULL) OR (\"OwnerKind\" = 2 AND \"InstanceId\" IS NOT NULL) OR (\"OwnerKind\" = 3 AND \"InstanceId\" IS NOT NULL) OR (\"OwnerKind\" = 4 AND \"RunnerId\" IS NOT NULL) OR (\"OwnerKind\" = 5 AND \"SubmissionId\" IS NOT NULL) OR (\"OwnerKind\" = 6 AND \"EvaluationJobId\" IS NOT NULL) OR (\"OwnerKind\" = 7 AND \"InstanceId\" IS NOT NULL) OR (\"OwnerKind\" = 8 AND \"InstanceId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_FileReferences_SingleOwner", "num_nonnulls(\"ProblemVersionId\", \"ActivityId\", \"SubmissionId\", \"EvaluationJobId\", \"RunnerId\", \"InstanceId\") = 1");
                        });
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Grant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedFromTemplate")
                        .HasColumnType("text");

                    b.Property<string>("GrantedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<bool>("OverrideSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("SourceProviderId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SourceProviderId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Grants_UserId_Manual")
                        .HasFilter("\"ActivityId\" IS NULL AND \"SourceProviderId\" IS NULL");

                    b.HasIndex("UserId", "ActivityId")
                        .IsUnique()
                        .HasFilter("\"ActivityId\" IS NOT NULL");

                    b.HasIndex("UserId", "SourceProviderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Grants_UserId_Provider")
                        .HasFilter("\"ActivityId\" IS NULL AND \"SourceProviderId\" IS NOT NULL");

                    b.HasIndex("ActivityId", "State", "IsSystem");

                    b.ToTable("Grants", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.IdentityProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ClaimPath")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DefaultTemplateName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("DeletionChannelEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("DeletionSecret")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("DeletionUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("UnmappedBehavior")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("IdentityProviders", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.IdentityProviderMappingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "ClaimValue")
                        .IsUnique();

                    b.ToTable("IdentityProviderMappingRules", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Instance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AccountDeletionEnabled")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("ExternalFetchHosts")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("ExternalJudgingEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("LocalRegistrationEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("RegisterRedirectProvider")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("RequireConfirmedEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireEmail")
                        .HasColumnType("boolean");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<bool>("SeriesRestrictionsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowLocalSignIn")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowLogo")
                        .HasColumnType("boolean");

                    b.Property<string>("SignInRedirectProvider")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("Instance", null, t =>
                        {
                            t.HasCheckConstraint("CK_Instance_Singleton", "\"Id\" = '00000000-0000-7000-8000-000000000001'");
                        });
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.MaintenanceState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("timestamptz");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Maintenance", null, t =>
                        {
                            t.HasCheckConstraint("CK_Maintenance_Singleton", "\"Id\" = '00000000-0000-7000-8000-000000000002'");
                        });
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.PermissionTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PermissionTemplates", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("External")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "Visibility");

                    b.ToTable("Problems", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.ProblemShare", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("ProblemId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProblemShares", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.ProblemVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Props")
                        .HasColumnType("jsonb");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProblemId", "Version")
                        .IsUnique();

                    b.ToTable("ProblemVersions", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerAuthorUserId")
                        .HasColumnType("text");

                    b.Property<string>("AnswerBody")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("AuthorUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeriesProblemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("SeriesProblemId");

                    b.HasIndex("ActivityId", "CreatedAt");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.QuestionRead", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("QuestionId", "UserId");

                    b.ToTable("QuestionReads", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("EvaluationJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Extra")
                        .HasColumnType("jsonb");

                    b.Property<double?>("MaxScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProblemVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Props")
                        .HasColumnType("jsonb");

                    b.Property<string>("RunnerVersion")
                        .HasColumnType("text");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("Verdict")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationJobId")
                        .IsUnique();

                    b.ToTable("Results", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Runner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("text");

                    b.Property<int>("CompletedJobs")
                        .HasColumnType("integer");

                    b.Property<bool>("External")
                        .HasColumnType("boolean");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Machine")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.PrimitiveCollection<List<string>>("ProblemTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Product")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("State");

                    b.ToTable("Runners", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndAnnouncedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("HideProblemsWhilePaused")
                        .HasColumnType("boolean");

                    b.Property<int>("Importance")
                        .HasColumnType("integer");

                    b.Property<int>("ImportanceScope")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("RankingFreezeAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("RankingRevealAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("RankingVisibleFrom")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("RankingVisibleTo")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("RestrictionsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("RevealProblemCount")
                        .HasColumnType("boolean");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.PrimitiveCollection<List<string>>("RunnerTags")
                        .HasColumnType("text[]");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("StartAnnouncedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("UnfrozenAnnouncedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("WindowAnnouncedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "Slug")
                        .IsUnique();

                    b.HasIndex("EndDate", "EndAnnouncedAt");

                    b.HasIndex("IsOpen", "Importance");

                    b.HasIndex("RankingRevealAt", "UnfrozenAnnouncedAt");

                    b.HasIndex("RankingVisibleFrom", "WindowAnnouncedAt");

                    b.HasIndex("StartDate", "StartAnnouncedAt");

                    b.ToTable("Series", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.SeriesAddressRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<IPNetwork>("Network")
                        .HasColumnType("cidr");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("SeriesAddressRules", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.SeriesProblem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Config")
                        .HasColumnType("jsonb");

                    b.Property<int?>("MaxAttachments")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxPoints")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxSubmissions")
                        .HasColumnType("integer");

                    b.Property<long?>("MaxUploadBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PinnedProblemVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Props")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Spec")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("PinnedProblemVersionId");

                    b.HasIndex("ProblemId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("ActivityId", "Slug")
                        .IsUnique();

                    b.ToTable("SeriesProblems", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.StorageMigration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("BytesMoved")
                        .HasColumnType("bigint");

                    b.Property<string>("Detail")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("FilesMoved")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamptz");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("TargetStoreId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.ToTable("StorageMigrations", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExcludedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ExcludedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ExclusionReason")
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet");

                    b.Property<string>("Props")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SeriesProblemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.HasIndex("SeriesProblemId", "UserId", "CreatedDate");

                    b.ToTable("Submissions", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Trial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Deliveries")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid");

                    b.Property<string>("Measurement")
                        .HasColumnType("text");

                    b.Property<Guid?>("PackageFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProblemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("RunnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("LeaseExpiresAt");

                    b.HasIndex("LeaseToken")
                        .IsUnique()
                        .HasFilter("\"LeaseToken\" IS NOT NULL");

                    b.HasIndex("RunnerId");

                    b.HasIndex("State", "CreatedAt");

                    b.ToTable("Trials", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Anonymized")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("BlockedReason")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.UserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastSignInAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProviderId", "Subject")
                        .IsUnique();

                    b.ToTable("UserIdentities", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamptz");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet");

                    b.Property<DateTime?>("LastRequestAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("LastRequestPath")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId", "EndedAt");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.AccountDeletionRequest", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.IdentityProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlgoJudge.Server.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Provider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.AccountMerge", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.User", "Source")
                        .WithMany()
                        .HasForeignKey("SourceUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Server.Database.Models.User", "Target")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.ActivityGroup", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.Activity", "Activity")
                        .WithMany("Groups")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.AttachmentRule", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.Activity", "Activity")
                        .WithMany("AttachmentRules")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.EvaluationJob", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.ProblemVersion", "ProblemVersion")
                        .WithMany()
                        .HasForeignKey("ProblemVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Server.Database.Models.Runner", "Runner")
                        .WithMany("Jobs")
                        .HasForeignKey("RunnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlgoJudge.Server.Database.Models.Submission", "Submission")
                        .WithMany("Jobs")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProblemVersion");

                    b.Navigation("Runner");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.FederatedSignInAttempt", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.IdentityProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.File", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.Runner", "UploadedByRunner")
                        .WithMany()
                        .HasForeignKey("UploadedByRunnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlgoJudge.Server.Database.Models.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UploadedBy");

                    b.Navigation("UploadedByRunner");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.FileReference", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlgoJudge.Server.Database.Models.EvaluationJob", "EvaluationJob")
                        .WithMany("Files")
                        .HasForeignKey("EvaluationJobId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlgoJudge.Server.Database.Models.File", "File")
                        .WithMany("References")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Server.Database.Models.Instance", "Instance")
                        .WithMany("Files")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlgoJudge.Server.Database.Models.ProblemVersion", "ProblemVersion")
                        .WithMany("Files")
                        .HasForeignKey("ProblemVersionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlgoJudge.Server.Database.Models.Runner", "Runner")
                        .WithMany("Files")
                        .HasForeignKey("RunnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlgoJudge.Server.Database.Models.Submission", "Submission")
                        .WithMany("Files")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Activity");

                    b.Navigation("EvaluationJob");

                    b.Navigation("File");

                    b.Navigation("Instance");

                    b.Navigation("ProblemVersion");

                    b.Navigation("Runner");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Grant", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.Activity", "Activity")
                        .WithMany("Grants")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlgoJudge.Server.Database.Models.ActivityGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlgoJudge.Server.Database.Models.IdentityProvider", "SourceProvider")
                        .WithMany()
                        .HasForeignKey("SourceProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlgoJudge.Server.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Group");

                    b.Navigation("SourceProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.IdentityProviderMappingRule", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.IdentityProvider", "Provider")
                        .WithMany("MappingRules")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Problem", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.ProblemShare", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.Problem", "Problem")
                        .WithMany("SharedWith")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Server.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.ProblemVersion", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlgoJudge.Server.Database.Models.Problem", "Problem")
                        .WithMany("Versions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Question", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.Activity", "Activity")
                        .WithMany("Questions")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Server.Database.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Server.Database.Models.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlgoJudge.Server.Database.Models.SeriesProblem", "SeriesProblem")
                        .WithMany("Questions")
                        .HasForeignKey("SeriesProblemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Activity");

                    b.Navigation("Author");

                    b.Navigation("Series");

                    b.Navigation("SeriesProblem");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.QuestionRead", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.Question", "Question")
                        .WithMany("Reads")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Result", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.EvaluationJob", "EvaluationJob")
                        .WithOne("Result")
                        .HasForeignKey("AlgoJudge.Server.Database.Models.Result", "EvaluationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationJob");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Series", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.Activity", "Activity")
                        .WithMany("Series")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.SeriesAddressRule", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.Series", "Series")
                        .WithMany("AddressRules")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.SeriesProblem", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Server.Database.Models.ProblemVersion", "PinnedProblemVersion")
                        .WithMany()
                        .HasForeignKey("PinnedProblemVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlgoJudge.Server.Database.Models.Problem", "Problem")
                        .WithMany("SeriesProblems")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Server.Database.Models.Series", "Series")
                        .WithMany("SeriesProblems")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("PinnedProblemVersion");

                    b.Navigation("Problem");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Submission", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.ActivityGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlgoJudge.Server.Database.Models.SeriesProblem", "SeriesProblem")
                        .WithMany("Submissions")
                        .HasForeignKey("SeriesProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Server.Database.Models.UserSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlgoJudge.Server.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("SeriesProblem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Trial", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlgoJudge.Server.Database.Models.Runner", "Runner")
                        .WithMany()
                        .HasForeignKey("RunnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Activity");

                    b.Navigation("Runner");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.UserIdentity", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.IdentityProvider", "Provider")
                        .WithMany("Identities")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Server.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.UserSession", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Server.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Activity", b =>
                {
                    b.Navigation("AttachmentRules");

                    b.Navigation("Grants");

                    b.Navigation("Groups");

                    b.Navigation("Questions");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.ActivityGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.EvaluationJob", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.File", b =>
                {
                    b.Navigation("References");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.IdentityProvider", b =>
                {
                    b.Navigation("Identities");

                    b.Navigation("MappingRules");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Instance", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Problem", b =>
                {
                    b.Navigation("SeriesProblems");

                    b.Navigation("SharedWith");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.ProblemVersion", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Question", b =>
                {
                    b.Navigation("Reads");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Runner", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Series", b =>
                {
                    b.Navigation("AddressRules");

                    b.Navigation("SeriesProblems");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.SeriesProblem", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Submission", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
