// <auto-generated />
using System;
using AlgoJudge.Server.Lti.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlgoJudge.Server.Lti.Migrations
{
    [DbContext(typeof(LtiDbContext))]
    partial class LtiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.DeepLinkSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AcceptMultiple")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextTitle")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<bool>("Embedded")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReturnUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PlatformId");

                    b.ToTable("LtiDeepLinkSessions", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssertedUsername")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLaunchAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId", "Subject")
                        .IsUnique();

                    b.HasIndex("PlatformId", "UserId")
                        .IsUnique();

                    b.ToTable("LtiExternalIdentities", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.GradeSyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<double>("DesiredScore")
                        .HasColumnType("double precision");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LineItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("PostedScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ResourceLinkId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceResultId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LineItemId", "UserId")
                        .IsUnique();

                    b.HasIndex("State", "NextAttemptAt");

                    b.ToTable("LtiGradeSyncStates", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.LaunchState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetLinkUri")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("State")
                        .IsUnique();

                    b.ToTable("LtiLaunchStates", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.LaunchTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Embedded")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<Guid>("ResourceLinkId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReturnUrl")
                        .HasColumnType("text");

                    b.Property<string>("Ticket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Ticket")
                        .IsUnique();

                    b.ToTable("LtiLaunchTickets", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.LineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlatformUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResourceLinkId")
                        .HasColumnType("uuid");

                    b.Property<double>("ScoreMaximum")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SeriesProblemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceLinkId", "SeriesProblemId")
                        .IsUnique();

                    b.ToTable("LtiLineItems", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.LtiSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AccountCreationEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LtiSettings", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthLoginUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthTokenUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeploymentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("IdentityNamespace")
                        .HasColumnType("text");

                    b.Property<bool>("IsIdentityAuthority")
                        .HasColumnType("boolean");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeySetUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsernameClaim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId")
                        .IsUnique();

                    b.HasIndex("Issuer", "ClientId", "DeploymentId")
                        .IsUnique();

                    b.ToTable("LtiPlatforms", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.RegistrationInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid?>("PlatformId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LtiRegistrationInvitations", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.ResourceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Aggregation")
                        .HasColumnType("integer");

                    b.Property<string>("AgsLineItemsUrl")
                        .HasColumnType("text");

                    b.Property<string>("ContextHistory")
                        .HasColumnType("text");

                    b.Property<string>("ContextId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextTitle")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NrpsMembershipsUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlatformResourceLinkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SharingAcknowledged")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("PlatformId", "PlatformResourceLinkId")
                        .IsUnique();

                    b.ToTable("LtiResourceLinks", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.ToolKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrivatePem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicPem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RetiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Kid")
                        .IsUnique();

                    b.ToTable("LtiToolKeys", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.DeepLinkSession", b =>
                {
                    b.HasOne("AlgoJudge.Server.Lti.Data.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.ExternalIdentity", b =>
                {
                    b.HasOne("AlgoJudge.Server.Lti.Data.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.GradeSyncState", b =>
                {
                    b.HasOne("AlgoJudge.Server.Lti.Data.LineItem", "LineItem")
                        .WithMany()
                        .HasForeignKey("LineItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LineItem");
                });

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.LineItem", b =>
                {
                    b.HasOne("AlgoJudge.Server.Lti.Data.ResourceLink", "ResourceLink")
                        .WithMany("LineItems")
                        .HasForeignKey("ResourceLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceLink");
                });

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.ResourceLink", b =>
                {
                    b.HasOne("AlgoJudge.Server.Lti.Data.Platform", "Platform")
                        .WithMany("ResourceLinks")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.Platform", b =>
                {
                    b.Navigation("ResourceLinks");
                });

            modelBuilder.Entity("AlgoJudge.Server.Lti.Data.ResourceLink", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
